spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: MyHikariCP
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show-sql: false

app:
  jwt:
    secret: testItWillBeChange
