spring:
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      password: 1234
      host: localhost
      port: 6379

app:
  jwt:
    secret-key: testItWillBeChangetestItWillBeChangetestItWillBeChangetestItWillBeChangetestItWillBeChangetestItWillBeChangetestItWillBeChange
    access: 35000
    refresh: 131231231